/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DpdkAccess */

#ifndef _Included_DpdkAccess
#define _Included_DpdkAccess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     DpdkAccess
 * Method:    nat_setup
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_DpdkAccess_nat_1setup
  (JNIEnv *, jclass);

/*
 * Class:     DpdkAccess
 * Method:    nat_receive_burst
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_DpdkAccess_nat_1receive_1burst
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
