/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DpdkAccess */

#ifndef _Included_DpdkAccess
#define _Included_DpdkAccess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     DpdkAccess
 * Method:    nat_setup
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_DpdkAccess_nat_1setup
  (JNIEnv *, jclass);

/*
 * Class:     DpdkAccess
 * Method:    nat_receive_burst
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_DpdkAccess_nat_1receive_1burst
  (JNIEnv *, jclass, jlong);

/*
 * Class:     DpdkAccess
 * Method:    nat_free_packets
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_DpdkAccess_nat_1free_1packets
  (JNIEnv *, jclass, jlong);

/*
 * Class:     DpdkAccess
 * Method:    nat_send_packets
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_DpdkAccess_nat_1send_1packets
  (JNIEnv *, jclass, jlong);

/*
 * Class:     DpdkAccess
 * Method:    nat_set_core_mask
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_DpdkAccess_nat_1set_1core_1mask
  (JNIEnv *, jclass, jstring);

/*
 * Class:     DpdkAccess
 * Method:    nat_set_port_mask
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_DpdkAccess_nat_1set_1port_1mask
  (JNIEnv *, jclass, jstring);

/*
 * Class:     DpdkAccess
 * Method:    nat_set_program_name
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_DpdkAccess_nat_1set_1program_1name
  (JNIEnv *, jclass, jstring);

/*
 * Class:     DpdkAccess
 * Method:    nat_set_memory_channels
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_DpdkAccess_nat_1set_1memory_1channels
  (JNIEnv *, jclass, jstring);

/*
 * Class:     DpdkAccess
 * Method:    nat_set_memory
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_DpdkAccess_nat_1set_1memory
  (JNIEnv *, jclass, jstring);

/*
 * Class:     DpdkAccess
 * Method:    nat_set_program_id
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_DpdkAccess_nat_1set_1program_1id
  (JNIEnv *, jclass, jstring);

/*
 * Class:     DpdkAccess
 * Method:    nat_set_blacklist
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_DpdkAccess_nat_1set_1blacklist
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
