/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DpdkAccess */

#ifndef _Included_DpdkAccess
#define _Included_DpdkAccess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     DpdkAccess
 * Method:    nat_setup
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_DpdkAccess_nat_1setup
  (JNIEnv *, jclass);

/*
 * Class:     DpdkAccess
 * Method:    nat_receive_burst
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_DpdkAccess_nat_1receive_1burst
  (JNIEnv *, jclass, jlong);

/*
 * Class:     DpdkAccess
 * Method:    nat_size_of_ether_hdr
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_DpdkAccess_nat_1size_1of_1ether_1hdr
  (JNIEnv *, jclass);

/*
 * Class:     DpdkAccess
 * Method:    nat_size_of_mbuf
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_DpdkAccess_nat_1size_1of_1mbuf
  (JNIEnv *, jclass);

/*
 * Class:     DpdkAccess
 * Method:    nat_size_of_void_pointer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_DpdkAccess_nat_1size_1of_1void_1pointer
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
