/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Wrapper */

#ifndef _Included_Wrapper
#define _Included_Wrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Wrapper
 * Method:    eal_init
 * Signature: ([Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_Wrapper_eal_1init
  (JNIEnv *, jclass, jobjectArray, jint);

#ifdef __cplusplus
}
#endif
#endif
