/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DpdkAccess */

#ifndef _Included_DpdkAccess
#define _Included_DpdkAccess
#ifdef __cplusplus
extern "C" {
#endif

//char *int_to_ip(uint32_t);

/*
 * Class:     DpdkAccess
 * Method:    nat_setup_and_conf
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_DpdkAccess_nat_1setup_1and_1conf
  (JNIEnv *, jclass, jobject);

/*
 * Class:     DpdkAccess
 * Method:    nat_get_packets
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_DpdkAccess_nat_1get_1packets
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
