/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Main */

#ifndef _Included_Main
#define _Included_Main
#ifdef __cplusplus
extern "C" {
#endif
#undef Main_REPETITIONS_1
#define Main_REPETITIONS_1 1000000L
#undef Main_REPETITIONS_2
#define Main_REPETITIONS_2 1000L
#undef Main_REPETITIONS
#define Main_REPETITIONS 1000L
/*
 * Class:     Main
 * Method:    getData
 * Signature: (LObjectPacket;)V
 */
JNIEXPORT void JNICALL Java_Main_getData__LObjectPacket_2
  (JNIEnv *, jclass, jobject);

/*
 * Class:     Main
 * Method:    setData
 * Signature: (LObjectPacket;)V
 */
JNIEXPORT void JNICALL Java_Main_setData__LObjectPacket_2
  (JNIEnv *, jclass, jobject);

/*
 * Class:     Main
 * Method:    getData
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_Main_getData__Ljava_nio_ByteBuffer_2
  (JNIEnv *, jclass, jobject);

/*
 * Class:     Main
 * Method:    setData
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_Main_setData__Ljava_nio_ByteBuffer_2
  (JNIEnv *, jclass, jobject);

/*
 * Class:     Main
 * Method:    getPointer
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_Main_getPointer
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
